/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrame;

import static jFrame.JFrameMenuPembeli.beli;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projectuas.cDaftarTransaksi;
import projectuas.cTransaksi;

/**
 *
 * @author rizka
 */
public class JFrameMenuMember extends javax.swing.JFrame {
    public static cDaftarTransaksi beli;
    /**
     * Creates new form JFrameMenuMember
     */
    
    int total = 0;
    
    public JFrameMenuMember() {
        initComponents();
        DefaultTableModel modelBr = (DefaultTableModel)listBarangMember.getModel();
        // Tampilkan barang 1
        String barang1[] = new String[2];
        barang1[0] = projectuas.MainApps.brg1.getNama();
        barang1[1] = String.valueOf((int) projectuas.MainApps.brg1.getHarga());
        modelBr.addRow(barang1);
        // Tampilkan barang 2
        String barang2[] = new String[2];
        barang2[0] = projectuas.MainApps.brg2.getNama();
        barang2[1] = String.valueOf((int) projectuas.MainApps.brg2.getHarga());
        modelBr.addRow(barang2);
        // Tampilkan barang 3
        String barang3[] = new String[2];
        barang3[0] = projectuas.MainApps.brg3.getNama();
        barang3[1] = String.valueOf((int) projectuas.MainApps.brg3.getHarga());
        modelBr.addRow(barang3);
        // Tampilkan barang 4
        String barang4[] = new String[2];
        barang4[0] = projectuas.MainApps.brg4.getNama();
        barang4[1] = String.valueOf((int) projectuas.MainApps.brg4.getHarga());
        modelBr.addRow(barang4);
        // Tampilkan barang 5
        String barang5[] = new String[2];
        barang5[0] = projectuas.MainApps.brg5.getNama();
        barang5[1] = String.valueOf((int) projectuas.MainApps.brg5.getHarga());
        modelBr.addRow(barang5);
        
        projectuas.MainApps.kode++;
        beli = new cDaftarTransaksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listBarangMember = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        KeranjangMember = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnTambahMbr = new javax.swing.JButton();
        btnCheckoutMember = new javax.swing.JButton();
        btnHapusMbr = new javax.swing.JButton();
        btnKeluarMbr = new javax.swing.JButton();
        btnUbahPw = new javax.swing.JButton();
        labelTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Keranjang");

        listBarangMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Barang", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listBarangMember);

        KeranjangMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Barang", "Jumlah", "Harga", "Diskon", "Sub Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(KeranjangMember);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Daftar Barang");

        btnTambahMbr.setBackground(new java.awt.Color(0, 153, 0));
        btnTambahMbr.setForeground(new java.awt.Color(0, 0, 0));
        btnTambahMbr.setText("Tambah");
        btnTambahMbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahMbrActionPerformed(evt);
            }
        });

        btnCheckoutMember.setBackground(new java.awt.Color(102, 102, 255));
        btnCheckoutMember.setForeground(new java.awt.Color(0, 0, 0));
        btnCheckoutMember.setText("Checkout");
        btnCheckoutMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutMemberActionPerformed(evt);
            }
        });

        btnHapusMbr.setBackground(new java.awt.Color(102, 102, 102));
        btnHapusMbr.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusMbr.setText("Hapus");
        btnHapusMbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusMbrActionPerformed(evt);
            }
        });

        btnKeluarMbr.setBackground(new java.awt.Color(255, 102, 102));
        btnKeluarMbr.setForeground(new java.awt.Color(0, 0, 0));
        btnKeluarMbr.setText("Keluar");
        btnKeluarMbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarMbrActionPerformed(evt);
            }
        });

        btnUbahPw.setBackground(new java.awt.Color(255, 204, 0));
        btnUbahPw.setForeground(new java.awt.Color(0, 0, 0));
        btnUbahPw.setText("Ubah Password");
        btnUbahPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahPwActionPerformed(evt);
            }
        });

        labelTotal.setBackground(new java.awt.Color(0, 0, 0));
        labelTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotal.setForeground(new java.awt.Color(0, 0, 0));
        labelTotal.setText("Total : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addGap(75, 75, 75)
                        .addComponent(labelTotal))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHapusMbr, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKeluarMbr, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUbahPw)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCheckoutMember, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTambahMbr, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahMbr, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckoutMember, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusMbr, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKeluarMbr, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbahPw, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahMbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahMbrActionPerformed
        // TODO add your handling code here:
        boolean tambah = false;
        String jb = JOptionPane.showInputDialog(this,"Masukkan jumlah barang : ");
        
        if(jb != null) {
            tambah = true;
        }
        
        if(tambah) {
            int jml = Integer.parseInt(jb);
            DefaultTableModel modelBr = (DefaultTableModel) listBarangMember.getModel();
            int row = listBarangMember.getSelectedRow();
            String barang = String.valueOf(modelBr.getValueAt(row, 0));
            if (barang.equalsIgnoreCase("panci")) {
                projectuas.MainApps.br = new cTransaksi( String.valueOf(projectuas.MainApps.kode), String.valueOf(JFrameMember.idMbr), projectuas.MainApps.brg1, jml, "Belum diproses", 1);
            } 
            else if (barang.equalsIgnoreCase("Blender")) {
                projectuas.MainApps.br = new cTransaksi( String.valueOf(projectuas.MainApps.kode), String.valueOf(JFrameMember.idMbr), projectuas.MainApps.brg2, jml, "Belum diproses", 2);
            }
            else if (barang.equalsIgnoreCase("Ulekan")) {
                projectuas.MainApps.br = new cTransaksi( String.valueOf(projectuas.MainApps.kode), String.valueOf(JFrameMember.idMbr), projectuas.MainApps.brg3, jml, "Belum diproses", 3);
            }
            else if (barang.equalsIgnoreCase("Mug")) {
                projectuas.MainApps.br = new cTransaksi( String.valueOf(projectuas.MainApps.kode), String.valueOf(JFrameMember.idMbr), projectuas.MainApps.brg4, jml, "Belum diproses", 4);
            }
            else if (barang.equalsIgnoreCase("Wajan")) {
                projectuas.MainApps.br = new cTransaksi( String.valueOf(projectuas.MainApps.kode), String.valueOf(JFrameMember.idMbr), projectuas.MainApps.brg5, jml, "Belum diproses", 5);
            }
            beli.AddTransaksi(projectuas.MainApps.br);
            projectuas.MainApps.jmlpesanan++;

            // Update Tabel Keranjang
            DefaultTableModel modelCart = (DefaultTableModel)KeranjangMember.getModel();

            String barangBaru[] = new String[5];
            barangBaru[0] = projectuas.MainApps.br.getBarang().getNama();
            barangBaru[1] = String.valueOf(jml);
            barangBaru[2] = String.valueOf(projectuas.MainApps.br.getBarang().getHarga());
            barangBaru[3] = String.valueOf(projectuas.MainApps.br.getBarang().getHarga()*0.05);
            
            
            int subtotal = 0;
            subtotal = (int) ((projectuas.MainApps.br.getBarang().getHarga()*0.95) * jml);
            //barangBaru[4] = String.valueOf((projectuas.MainApps.br.getBarang().getHarga()*0.95) * jml);
            barangBaru[4] = String.valueOf(subtotal);
            total = total+subtotal;
            modelCart.addRow(barangBaru);
            labelTotal.setText("Total : "+total);
//            if (JFrameMember.idl==1) {
//                labelTotal.setText("Total"+projectuas.MainApps.jual.totalmem10());
//            }else if (JFrameMember.id2==2) {
//                labelTotal.setText("Total"+projectuas.MainApps.jual.totalmem11());
//            }else if (JFrameMember.id3 == 3) {
//                labelTotal.setText("Total"+projectuas.MainApps.jual.totalmem12());
//            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Batal menambahkan!");
        }
        
    }//GEN-LAST:event_btnTambahMbrActionPerformed

    private void btnHapusMbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusMbrActionPerformed
        // TODO add your handling code here:
        int j = JOptionPane.showConfirmDialog(this, "Yakin dihapus?");
        if (j==0) {
            DefaultTableModel modelCart = (DefaultTableModel)KeranjangMember.getModel();
            int row = KeranjangMember.getSelectedRow();
            int nomor = row+1;
            beli.DeleteTransaksi(nomor);
            modelCart.removeRow(row);
            projectuas.MainApps.jmlpesanan--;
        } else {
            JOptionPane.showMessageDialog(null, "Batal dihapus!");
        }
    }//GEN-LAST:event_btnHapusMbrActionPerformed

    private void btnKeluarMbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarMbrActionPerformed
        // TODO add your handling code here:
        new jFrame.JFrameHome().show();
        this.dispose();
        
    }//GEN-LAST:event_btnKeluarMbrActionPerformed

    private void btnCheckoutMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutMemberActionPerformed
        // TODO add your handling code here:
        if(beli.getFront() != null) {
            projectuas.MainApps.jual.sambung(beli.getFront(), beli.getRear());
            JOptionPane.showMessageDialog(this, "Pesanan berhasil disimpan!");
        }
        else {
            JOptionPane.showMessageDialog(this, "Order batal...");
        }
    }//GEN-LAST:event_btnCheckoutMemberActionPerformed

    private void btnUbahPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahPwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahPwActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMenuMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable KeranjangMember;
    private javax.swing.JButton btnCheckoutMember;
    private javax.swing.JButton btnHapusMbr;
    private javax.swing.JButton btnKeluarMbr;
    private javax.swing.JButton btnTambahMbr;
    private javax.swing.JButton btnUbahPw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JTable listBarangMember;
    // End of variables declaration//GEN-END:variables
}
